### ISSUE TITLE
Video in url is not valid

### ISSUE THREAD

**Issue by zupat** [zezo357/flutter_meedu_videoplayer_example#1]
The url used in this example no longer works. It'd be better to upload a sample video directly to github.
```
https://movietrailers.apple.com/movies/paramount/the-spongebob-movie-sponge-on-the-run/the-spongebob-movie-sponge-on-the-run-big-game_h720p.mov
```

**Comment by abdelaziz-mahdy** [comment]
if you can provide a pr on main repo that will be awesome https://github.com/zezo357/flutter_meedu_videoplayer

**Comment by zupat** [comment]
Done: https://github.com/zezo357/flutter_meedu_videoplayer/pull/181
